"""000

Revision ID: 551fdbedab78
Revises: 
Create Date: 2022-05-12 14:00:02.622355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551fdbedab78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mettingroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mettingroom')
    # ### end Alembic commands ###
